# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "generic/fedora37"
  config.vm.synced_folder ".", "/vagrant"

  config.vm.hostname = "myhost.fedora-1"
  config.vm.network "private_network", type: "dhcp"
end
