---
- name: ensure apt-transport-https
  apt:
    name: 
      - apt-transport-https
      - ca-certificates
    update_cache: true
    state: latest

- name: ensure keyrings dir
  file:
    path: /etc/apt/keyrings
    state: directory

- name: install gpg key
  ansible.builtin.get_url:
    url: https://packages.adoptium.net/artifactory/api/gpg/key/public
    dest: /etc/apt/keyrings/adoptium.asc

- name: install repo
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/adoptium.asc] https://packages.adoptium.net/artifactory/deb bionic main"
    filename: /etc/apt/sources.list.d/adoptium.list
    state: present

- name: install jdk-8
  apt:
    name:
      - temurin-8-jdk
    update_cache: true
    state: present