---
- name: Add sonatype-community repo
  apt_repository:
    repo: "deb [arch=all trusted=yes] https://repo.sonatype.com/repository/community-apt-hosted/ bionic main"
    state: present

- name: install Nexus
  apt:
    name: nexus-repository-manager
    state: latest
    
- name: wait for nexus restart
  wait_for:
    host: localhost
    port: 8081
    state: started
    timeout: 240

- name: summary
  debug:
    msg: "Running Nexus on port 8081"
    
- name: check if initial admin passwd exists
  stat:
    path: /opt/sonatype/sonatype-work/nexus3/admin.password
  register: pn

- name: create nexus user
  script:
    cmd: security-users.sh "admin:admin123"
  when: pn.stat.exists
  
- name: create docker-snapshots repo
  script:
    cmd: sh repositories-docker-hosted.sh "admin:admin123" "docker-snapshots.json" 
  when: pn.stat.exists

- name: create docker-releases repo
  script: 
    cmd: sh repositories-docker-hosted.sh "admin:admin123" "docker-releases.json" 
  when: pn.stat.exists

- name: read admin passwd
  shell: |
    cat /opt/sonatype/sonatype-work/nexus3/admin.password
  when: pn.stat.exists
  register: nexus_passwd

- name: print nexus passwd
  debug:
    msg: "INITIAL NEXUS ADMIN PASSWD: {{ nexus_passwd.stdout }}"
  when: pn.stat.exists

