---
- name: check if keystore already exists
  stat:
    path: "/opt/sonatype/nexus3/etc/ssl/keystore.jks"
  register: keystore

- name: generate keystore
  shell:
    chdir: /opt/sonatype/nexus3/etc/ssl
    cmd: 'keytool -genkeypair -keystore keystore.jks -storepass password -keypass password -alias jetty -keyalg RSA -keysize 2048 -validity 5000 -dname "CN=*.192.168.56.5, OU=Example, O=Sonatype, L=Unspecified, ST=Unspecified, C=US" -ext "SAN=DNS:192.168.56.5,IP:192.168.56.5" -ext "BC=ca:true"'
  when: not keystore.stat.exists

- name: ensure nexus.properties ssl port
  lineinfile:
    dest: "{{ nexus_prop_path }}"
    line: "application-port-ssl=8443"
    insertafter: "application-port="
    firstmatch: true
    backup: true

- name: ensure nexus args (nexus.properties)
  lineinfile:
    path: "{{ nexus_prop_path }}"
    regexp: (?i)^\s*#\s*(nexus-args=.*jetty-http.xml,)(\${jetty.etc}/jetty-requestlog.xml.*)
    line: \1${jetty.etc}/jetty-https.xml,\2
    backrefs: yes
    backup: true

- name: ssl.etc in nexus.prop
  lineinfile:
    path: "{{ nexus_prop_path }}"
    line: "ssl.etc=/opt/sonatype/nexus3/etc/ssl"
    backup: true

- name: jetty cert alias
  lineinfile:
    dest: /opt/sonatype/nexus3/etc/jetty/jetty-https.xml
    line: '<Set name="certAlias">jetty</Set>'
    firstmatch: true
    insertbefore: '<Set name="KeyStorePath">'
    backup: true

- name: restart nexus service
  systemd:
    daemon_reload: true
    name: nexus-repository-manager.service
    state: restarted
