---
- name: ensure docker service is started
  systemd:
    name: docker.service
    state: started
    enabled: true

- name: wait for docker 
  wait_for:
    host: localhost
    port: 2376
    state: started
    timeout: 120

- name: copy Dockerfile
  copy: 
    src: jenkins-docker-jdk17
    dest: /home/vagrant/docker/

- name: build lipalipinski/jenkins-docker-jdk17
  community.docker.docker_image:
    name: lipalipinski/jenkins-docker-jdk17
    build:
      path: /home/vagrant/docker/jenkins-docker-jdk17
    source: build