---
- name: reset ssh connection
  meta: reset_connection

- name: update apt cache
  apt:
    update-cache: true

- name: restart jenkins
  systemd:
    daemon_reload: true
    name: jenkins
    state: restarted
    enabled: true

- name: restart nexus
  systemd:
    daemon_reload: true
    name: nexus-repository-manager.service
    state: restarted

- name: restart docker
  systemd:
    daemon_reload: true
    name: docker.service
    state: restarted
    enabled: true