---
- name: ensure cert dir
  file:
    path: "{{ cert_dir }}/{{ item.dir }}"
    state: directory
    recurse: true
  loop:
    - { dir: 192.168.56.5:8443 }
    - { dir: 192.168.56.5:18443 }
    - { dir: 192.168.56.5:18444 }

- name: check if :8443 cert exists
  stat: 
    path: "{{ cert_dir }}/192.168.56.5:8443/ca.crt"
  register: cert0

- name: check if :18443 cert exists
  stat: 
    path: "{{ cert_dir }}/192.168.56.5:18443/ca.crt"
  register: cert1

- name: check if :18444 cert exists
  stat: 
    path: "{{ cert_dir }}/192.168.56.5:18444/ca.crt"
  register: cert2

- name: wait for nexus restart
  wait_for:
    host: 192.168.56.5
    port: 8443
    state: started
    timeout: 120

- name: write to cert file (8443)
  shell:
    executable: /bin/bash
    chdir: "{{ cert_dir }}/192.168.56.5:8443"
    creates: "ca.crt"
    cmd: "keytool -rfc -printcert -sslserver 192.168.56.5:8443 | sudo tee ca.crt > /dev/null"
  when: 
    - not cert0.stat.exists 
  notify: restart docker
  
- name: copy ca.crt
  copy:
    remote_src: true 
    src: "{{ cert_dir }}/192.168.56.5:8443/ca.crt"
    dest: "{{ cert_dir }}/192.168.56.5:{{ item }}/ca.crt"
  when:
    - not cert1.stat.exists or
      not cert2.stat.exists 
  with_items:
    - "18443"
    - "18444"