---
- name: ensure cert dir
  file:
    path: "{{ cert_dir }}/{{ item.dir }}"
    state: directory
    recurse: true
  loop:
    - { dir: 192.168.56.5:18443 }
    - { dir: 192.168.56.5:18444 }

- name: check if :18443 cert exists
  stat: 
    path: "{{ cert_dir }}/192.168.56.5:18443/ca.crt"
  register: cert1

- name: check if :18444 cert exists
  stat: 
    path: "{{ cert_dir }}/192.168.56.5:18444/ca.crt"
  register: cert2

- name: wait for nexus restart
  wait_for:
    host: 192.168.56.5
    port: 8443
    state: started
    timeout: 120

- name: write to cert file
  shell:
    executable: /bin/bash
    chdir: "{{ cert_dir }}/192.168.56.5:18443"
    creates: "ca.crt"
    cmd: "keytool -rfc -printcert -sslserver 192.168.56.5:18443 | sudo tee ca.crt > /dev/null"
  when: not cert1.stat.exists
  notify: restart docker

- name: write to cert file
  shell:
    executable: /bin/bash
    chdir: "{{ cert_dir }}/192.168.56.5:18444"
    creates: "ca.crt"
    cmd: "keytool -rfc -printcert -sslserver 192.168.56.5:18444 | sudo tee ca.crt > /dev/null"
  when: not cert2.stat.exists
  notify: restart docker

#- name: docker login
#  docker_login:
#    registry_url: 192.168.56.5:18443
#    tls_hostname: 192.168.56.3
#    ca_cert: "{{ cert_dir }}/ca.crt"
#    username: admin
#    password: admin123
#    config_path: /home/vagrant/.docker/config.json

#- name: docker config.json
#  file:
#    path: /home/vagrant/.docker/config.json
#    mode: '0644'
