---
- name: ensure cert dir
  file:
    path: "{{ cert_dir }}"
    state: directory
    recurse: true

- name: check if cert exists
  stat: 
    path: "{{ cert_dir }}/ca.crt"
  register: cert

- name: wait for nexus restart
  wait_for:
    host: 192.168.56.5
    port: 8443
    state: started
    timeout: 120

- name: write to cert file
  shell:
    executable: /bin/bash
    chdir: "{{ cert_dir }}"
    creates: "ca.crt"
    cmd: "keytool -rfc -printcert -sslserver 192.168.56.5:8443 | sudo tee ca.crt > /dev/null"
  when: not cert.stat.exists

- name: docker login
  docker_login:
    registry_url: 192.168.56.5:18443
    tls_hostname: 192.168.56.3
    ca_cert: "{{ cert_dir }}/ca.crt"
    username: admin
    password: admin123
    config_path: /home/vagrant/.docker/config.json

- name: docker config.json
  file:
    path: /home/vagrant/.docker/config.json
    mode: '0644'

