---

- name: update packages
  hosts: all
  become: true
  roles: 
    - update

- name: install tools
  hosts: all
  become: true
  tasks:
    
    - apt:
        name:
          - git
          - vim
          - tree
        state: latest
