---
- name: update packages
  hosts: all
  become: true
  roles: 
    - update

- name: install tools
  hosts: all
  become: true
  roles:
    - install-tools
    - install-jdk-17

- name: install nexus
  hosts: nexus
  become: true
  roles:
    - install-jdk-8
    - install-nexus

- name: nexus ssl cert
  hosts: nexus
  become: true
  roles:
    - nexus-ssl

- name: instal jenkins
  hosts: jenkins
  become: true
  roles:
    - install-jenkins
    - start-jenkins

- name: install docker
  hosts: docker
  become: true
  roles:
    - install-docker

- name: docker ssl cert
  hosts: docker
  become: true
  roles:
    - docker-ssl
