---

- name: update packages
  hosts: all
  strategy: free
  become: true
  roles: 
    - update

- name: install tools
  strategy: free
  hosts: all
  become: true
  tasks:
    
    - apt:
        name:
          - git
          - vim
          - tree
          - htop
        state: latest

- name: install nexus
  strategy: free
  hosts: nexus
  become: true
  roles:
    - install-nexus
