---
- name: install tools
  hosts: all
  become: true
  strategy: free
  roles:
    - update
    - install-tools

- name: install jdk-11 & jdk-17
  hosts: 
    - jenkins
    - docker
  become: true
  strategy: free
  roles:
    - install-jdk-11
    - install-jdk-17

- name: install nexus
  hosts: nexus
  become: true
  roles:
    - install-jdk-8
    - install-nexus
    - nexus-ssl

- name: instal jenkins
  hosts: jenkins
  become: true
  roles:
    - install-jenkins
    - start-jenkins

- name: install docker
  hosts: docker
  become: true
  roles:
    - install-docker
    - docker-ssl
