---
- name: update packages
  hosts: all
  strategy: free
  become: true
  roles: 
    - update

- name: install tools
  strategy: free
  hosts: all
  become: true
  roles:
    - install-tools

- name: install nexus
  strategy: free
  hosts: nexus
  become: true
  roles:
    - install-nexus

- name: nexus ssl cert
  hosts: nexus
  become: true
  roles:
    - nexus-ssl

- name: instal jenkins
  strategy: free
  hosts: jenkins
  become: true
  roles:
    - install-jenkins
    - start-jenkins

- name: install docker
  strategy: free
  hosts: docker
  become: true
  roles:
    - install-docker

- name: docker ssl cert
  hosts: docker
  become: true
  roles:
    - docker-ssl
