---

- name: update packages
  hosts: all
  strategy: free
  become: true
  roles: 
    - update

- name: install tools
  strategy: free
  hosts: all
  become: true
  tasks:
    
    - apt:
        name:
          - ca-certificates
          - curl
          - git
          - gnupg
          - htop
          - tree
          - vim
        state: latest

- name: install nexus
  strategy: free
  hosts: nexus
  become: true
  roles:
    - install-nexus

- name: install docker
  strategy: free
  hosts: docker
  become: true
  roles:
    - install-docker
