---

- name: update cache
  hosts: all
  become: true
  roles: 
    - update

- name: install tools
  hosts: all
  become: true
  tasks:
    
    - package:
        name:
          - git
          - vim
        state: present
