---
- name: Install Jenkins key
  apt_key:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
    state: present

- name: Add Jenkins repo
  apt_repository:
    repo: "deb https://pkg.jenkins.io/debian-stable binary/"
    state: present

- name: apt update
  apt:
    update-cache: true

- name: install java 11
  apt:
    name: openjdk-11-jdk
    state: latest

- name: install Jenkins
  apt:
    name: jenkins
    state: latest

- name: check if initial passwd exists
  stat:
    path: /var/lib/jenkins/secrets/initialAdminPassword
  register: p

- name: read initial admin pass
  shell: |
    cat /var/lib/jenkins/secrets/initialAdminPassword
  when: p.stat.exists
  register: adm_passwd

- name: print initial admin passwd
  debug:
    msg: "INITIAL JENKINS ADMIN PASSWD: {{ adm_passwd.stdout }}"
  when: p.stat.exists
  
