--- 
- name: uninstall any old docker
  apt:
    name:
      - remove
      - docker 
      - docker-engine 
      - docker.io 
      - containerd 
      - runc
    state: absent

- name: install gpg key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  notify: update apt cache

- name: add docker repo
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
  notify: update apt cache

- name: update apt cache
  meta: flush_handlers

- name: install docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest
  notify: restart docker

- name: expose socket on 2376
  lineinfile:
    path: /lib/systemd/system/docker.service
    regexp: '^ExecStart='
    line: ExecStart=/usr/bin/dockerd -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock
  notify: restart docker

- name: run docker without sudo
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true
  register: user_group

- name: reboot after adding user to group
  reboot:
  when: user_group.changed

- name: flush handlers
  meta: flush_handlers