---
- name: uninstall any old docker
  apt:
    name:
      - remove
      - docker 
      - docker-engine 
      - docker.io 
      - containerd 
      - runc
    state: absent

- name: install gpg key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add docker repo
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: apt update
  apt:
    update-cache: true
    
- name: install docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest

- name: start docker service
  service:
    name: docker
    state: started
    enabled: true

- name: run docker without sudo
  user:
    name: vagrant
    groups: docker
    append: true

#- name: open ports
#  firewalld:
#    port: 4243/tcp
#    state: enabled
#    permanent: true
#    immediate: true
