---

- name: install dnf-plugins-core
  dnf:
    name: dnf-plugins-core
    state: installed

- name: install repo
  shell: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo

- name: install docker
  dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: installed

- name: start docker service
  service:
    name: docker
    state: started
    enabled: true

- name: open ports
  firewalld:
    port: 4243/tcp
    state: enabled
    permanent: true
    immediate: true
