--- 
- name: uninstall any old docker
  apt:
    name:
      - remove
      - docker 
      - docker-engine 
      - docker.io 
      - containerd 
      - runc
    state: absent

- name: install gpg key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  notify: update apt cache

- name: add docker repo
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
  notify: update apt cache

- name: update apt cache
  meta: flush_handlers

- name: install docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest

- name: start docker service
  service:
    name: docker
    state: started
    enabled: true

- name: run docker without sudo
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true
  register: user_group

- name: reboot after adding user to group
  reboot:
  when: user_group.changed